<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XE-T-DEEPAKS" ignored="0" name="Login With Email" tests="2" failures="1" timestamp="18 May 2017 08:37:50 GMT" time="14.804" errors="0">
  <testcase name="validateButtons" time="2.817" classname="testcases.care.CareLoginTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
	at testcases.care.CareLoginTest.validateButtons(CareLoginTest.java:31)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- validateButtons -->
  <testcase name="signUpEmailandSelectACareGiver" time="4.106" classname="testcases.care.CareLoginTest"/>
</testsuite> <!-- Login With Email -->
